name: morpheus3d
channels:
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - openpyxl
  - biopython
  - pip
  - scipy
  - tqdm
  - pandas=2.3.3
  - numpy=1.26.4
  - scikit-learn=1.6.1
  - joblib=1.5.3
